### ISSUE TITLE
获取不到nacos信息

### ISSUE THREAD

**Issue by justyida** [typ431127/Nacos_check#1]
nacos版本2.2.0报错：

/opt/application]# ./nacos-check --url http://10.21.1.xxx:8848
请求状态码异常:501
 /opt/application]# ./nacos-check --url http://10.21.1.xxx:8848/nacos
请求状态码异常:404
 /opt/application]# ./nacos-check --url http://10.21.1.xxx:8848/nacos/
请求状态码异常:500

登陆的网页是http://xxx.xxx.xxx.xxx:8848/nacos/#/login
是不是没有输入密码或者没有获取token啊，可是我用的是默认的nacos密码啊

**Comment by typ431127** [comment]
> nacos版本2.2.0报错：
> 
> /opt/application]# ./nacos-check --url http://10.21.1.xxx:8848 请求状态码异常:501 /opt/application]# ./nacos-check --url http://10.21.1.xxx:8848/nacos 请求状态码异常:404 /opt/application]# ./nacos-check --url http://10.21.1.xxx:8848/nacos/ 请求状态码异常:500
> 
> 登陆的网页是http://xxx.xxx.xxx.xxx:8848/nacos/#/login 是不是没有输入密码或者没有获取token啊，可是我用的是默认的nacos密码啊

nacos配置认证了吗?

**Comment by typ431127** [comment]
下载新版本使用就没有问题了,0.6版本
https://github.com/typ431127/Nacos_check/releases
